package collector

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"log/slog"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"golang.org/x/sys/unix"

	"github.com/skpr/compass/collector/internal/event/manager"
	"github.com/skpr/compass/collector/internal/usdt"
	"github.com/skpr/compass/collector/plugin"
)

const (
	ProbeProvider            = "compass"
	ProbeNameRequestShutdown = "request_shutdown"
	ProbeNameFunction        = "php_function"
)

//go:generate bpf2go -target amd64 -type event bpf program.bpf.c -- -I./headers

func Run(ctx context.Context, logger *slog.Logger, executablePath string, plugin plugin.Interface) error {
	logger.Info("Loading probes")

	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("failed to remove memlock rlimit: %w", err)
	}

	// Load pre-compiled programs and maps into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		return fmt.Errorf("failed to load objects: %w", err)
	}
	defer objs.Close()

	logger.Info("Opening executable")

	ex, err := link.OpenExecutable(executablePath)
	if err != nil {
		return fmt.Errorf("failed to open executable: %w", err)
	}

	logger.Info("Attaching probes")

	probeFunction, err := attachProbe(ex, executablePath, ProbeProvider, ProbeNameFunction, objs.UprobeCompassPhpFunction)
	if err != nil {
		return fmt.Errorf("failed to attach probe: %s: %w", ProbeNameFunction, err)
	}
	defer probeFunction.Close()

	probeRequest, err := attachProbe(ex, executablePath, ProbeProvider, ProbeNameRequestShutdown, objs.UprobeCompassRequestShutdown)
	if err != nil {
		return fmt.Errorf("failed to attach probe: %s: %w", ProbeNameRequestShutdown, err)
	}
	defer probeRequest.Close()

	logger.Info("Starting event mangaer..")

	manager, err := manager.New()
	if err != nil {
		return fmt.Errorf("unable to initialize event manager: %w", err)
	}

	logger.Info("Listening for events..")

	reader, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		return fmt.Errorf("failed to start perf event reader: %w", err)
	}
	defer reader.Close()

	// bpfEvent is generated by bpf2go.
	var event bpfEvent

	for {
		select {
		case <-ctx.Done():
			return reader.Close()
		default:
			record, err := reader.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					return err
				}

				logger.Info("reading from perf event reader:", err)
				continue
			}

			// Parse the perf event entry into a bpfEvent structure.
			if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event); err != nil {
				return fmt.Errorf("failed to parse event: %w", err)
			}

			var eventType = unix.ByteSliceToString(event.Type[:])

			switch eventType {
			case "function":
				if err := processFunction(logger, manager, event); err != nil {
					logger.Error("failed to process function: %w", err)
				}
			case "request_shutdown":
				if err := processRequestShutdown(logger, manager, plugin, event); err != nil {
					logger.Error("failed to request shutdown: %w", err)
				}
			}
		}
	}
}

func processFunction(logger *slog.Logger, manager *manager.Client, event bpfEvent) error {
	var (
		requestID    = unix.ByteSliceToString(event.RequestId[:])
		functionName = unix.ByteSliceToString(event.FunctionName[:])
	)

	logger.Debug("function event has been called", "request_id", requestID, "function_name", functionName, "execution_time", event.ExecutionTime)

	err := manager.AddFunction(requestID, functionName, event.ExecutionTime, time.Minute)
	if err != nil {
		log.Printf("failed to add function to event manager: %s", err)
	}

	return nil
}

func processRequestShutdown(logger *slog.Logger, manager *manager.Client, plugin plugin.Interface, event bpfEvent) error {
	var requestID = unix.ByteSliceToString(event.RequestId[:])

	logger.Debug("request shutdown event has been called", "request_id", requestID)

	request, err := manager.FlushRequest(requestID)
	if err != nil {
		return fmt.Errorf("failed to flush request: %w", err)
	}

	logger.Debug("request event has associated functions", "count", len(request.Functions))

	err = plugin.ProcessRequest(request)
	if err != nil {
		return fmt.Errorf("failed to send profile data to plugin: %w", err)
	}

	return nil
}

// Helper function to lookup the (usdt) probes location and attach our eBPF program to it.
func attachProbe(ex *link.Executable, executable, provider, probe string, prog *ebpf.Program) (link.Link, error) {
	locationFunctionBegin, err := usdt.GetLocationFromProbe(executable, provider, probe)
	if err != nil {
		return nil, fmt.Errorf("failed to get probe location: %s: %w", probe, err)
	}

	return ex.Uprobe(getSymbol(provider, probe), prog, &link.UprobeOptions{
		Address:      locationFunctionBegin.Location,
		RefCtrOffset: locationFunctionBegin.SemaphoreOffsetRefctr,
	})
}

func getSymbol(provider, function string) string {
	return fmt.Sprintf("usdt_%s_%s", provider, function)
}
