name: Bulk Update Go Dependencies

#on:
#  schedule:
#    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC
#  workflow_dispatch:

on:
  push:
    branches:
      - 'patchy-test'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for branch existence checks

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Configure Git
        run: |
          git config user.name "Patchy Bot"
          git config user.email "skprbot@skpr.com.au"

      - name: Check if branch exists
        id: check_branch
        run: |
          if git ls-remote --exit-code --heads origin patchy; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Go dependencies
        run: |
          go get -u ./...
          go mod tidy

      - name: Create or update branch
        run: |
          if [ "${{ steps.check_branch.outputs.exists }}" == "true" ]; then
            git stash push -m "pre-checkout changes"
            git fetch origin patchy
            git checkout patchy
            git stash pop || true  # Restore changes, ignore if nothing was stashed
          else
            git checkout -b patchy
          fi

          git add go.mod go.sum
          git commit -m "chore: bulk update Go dependencies" || echo "No changes to commit"
          git push origin patchy --force

      - name: Check if PR already exists
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr list --head patchy --json number --jq '.[].number' | grep -q '[0-9]'; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request if not exists
        if: steps.check_pr.outputs.pr_exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --head patchy \
            --title "chore: bulk update Go dependencies" \
            --body "This PR updates all Go dependencies using \`go get -u ./...\` and \`go mod tidy\`." \
            --base main
