name: 📋 Performance Test

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

concurrency:
  group: performance-test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  K6_SCRIPTS_DIR: ./performance-testing/scripts
  K6_SCENARIO: ./performance-testing/scenarios/basic.js
  K6_RESULTS_DIR: ./performance-testing/results

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v3

      - name: 📁 Init
        run: |
          # Create performance testing results directory.
          sudo mkdir -p ${K6_RESULTS_DIR}
          sudo chmod 777 ${K6_RESULTS_DIR}

      - name: 📦 Build Images
        run: |
          docker build -t localhost/compass:nginx-latest docker/compose/nginx
          docker build -t localhost/compass:php-fpm-latest docker/compose/php-fpm
          docker build --no-cache --build-arg=PHP_VERSION=8.3 -t localhost/compass:extension-latest extension
          docker build -t localhost/compass:php-fpm-ext-latest docker/compose/php-fpm-ext

      - name: 📦 Setup
        run: |
          docker compose up -d --wait
          docker compose exec --user=root php-fpm chown skpr:skpr /data/app/sites/default/files
          docker compose exec --user=root php-fpm chown skpr:skpr /mnt/private
          docker compose exec --user=root php-fpm chown skpr:skpr /mnt/temporary
          docker compose exec -e PHP_MEMORY_LIMIT=512M php-fpm vendor/bin/drush si demo_umami
      
      - name: 🧪 K6 - Execute Baseline Performance Test
        run: |
          bash ${K6_SCRIPTS_DIR}/k6_run.sh ${K6_SCENARIO} ${K6_RESULTS_DIR} baseline.json

      - name: ⚙️ Enable Extension
        run: |
          docker compose stop
          IMAGE_PHP_FPM=localhost/compass:php-fpm-ext-latest docker compose up -d --wait

      - name: 🧪 K6 - Execute Extension Enabled Performance Test
        run: |
          bash ${K6_SCRIPTS_DIR}/k6_run.sh ${K6_SCENARIO} ${K6_RESULTS_DIR} ext.json

      - name: 📋 Review Test Results
        run: |
          BUDGET=200
          bash ${K6_SCRIPTS_DIR}/review_results.sh ${K6_RESULTS_DIR}/baseline.json ${K6_RESULTS_DIR}/ext.json ${BUDGET} ${K6_RESULTS_DIR}/comment.txt

      - name: 📦 Collect Test Result Comment Details
        id: comment
        if: always()
        run: |
          results=$(cat ${K6_RESULTS_DIR}/comment.txt)
          echo "results=$results" >> "$GITHUB_OUTPUT"

      - name: 📋 Print Logs
        if: failure()
        run: |
          docker compose logs nginx
          docker compose logs php-fpm

      - name: 📋 Post Test Results to Comment
        uses: peter-evans/create-or-update-comment@v4
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Performance Data
            ----------------
            ${{ steps.comment.outputs.results }}
