name: "📋 Release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+[0-9A-Za-z]?'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Release ${{ matrix.component }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - component: cli
            image: ${{ github.repository }}
            os: ubuntu-latest
            arch: amd64
          - component: cli
            image: ${{ github.repository }}
            os: ubuntu-24.04-arm
            arch: arm64
          - component: sidecar
            image: ${{ github.repository }}-sidecar
            os: ubuntu-latest
            arch: amd64
          - component: sidecar
            image: ${{ github.repository }}-sidecar
            os: ubuntu-24.04-arm
            arch: arm64

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v4

      - name: 🔐 Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build and Push
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ matrix.image }}:${{ github.ref_name }}-${{ matrix.arch }}
          docker build --no-cache --target=${{ matrix.component }} -t ${IMAGE} .
          docker push ${IMAGE}

  manifest:
    name: Manifest ${{ matrix.component }}
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        include:
          - component: cli
            image: ${{ github.repository }}
          - component: sidecar
            image: ${{ github.repository }}-sidecar

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: 🔐 Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ☁️ Push
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ matrix.image }}:${{ github.ref_name }}
          docker manifest create ${IMAGE} --amend ${IMAGE}-arm64 --amend ${IMAGE}-amd64
          docker manifest push ${IMAGE}
